---
title: "Next Word Predictor"
author: "Utkarsh Chauhan"
date: "9/24/2020"
output: slidy_presentation
---

## Introduction

This slide is for the final project of the Coursera Data Science Capstone Course. The project is about building a predictive model to recommend the next best word given some input word(s).

As a fun idea I also included a sentence generator which generates upto 6 words on given input words.

The model was built using R and developed into a Shiny application running [here](https://im-utkarsh.shinyapps.io/next-word/)

## Application

Data used for this model is available [here](https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip). This is a 556MB data provided by SwiftKey containing 4 languages. For this app we primerly used 1% of the engilsh data given.

The main challenge is to create an application which can predict the next word regarding a sequence of words given by the user.

We used three datasets biWords.RData, triWords.RData and quadWords.RData (generated by the data mentioned above) which contains 2,3, and 4 words respectively along with their occurrence frequency.

Prediction and sentence generation is done using these datasets.

## Word Prediction Model

Compressed data sets containing descending frequency sorted n-grams are first loaded.

User input words are cleaned in the similar way as before prior to prediction of the next word.

For prediction of the next word, Quadgram is first used (first three words of Quadgram are the last three words of the user provided sentence).

If no Quadgram is found, back off to Trigram and so on until we hit Bigram.

If no Bigram is found, a '?' is returned.

An exploratory analysis of the data can be found [here](https://rpubs.com/utkarsh_chauhan/663931)

# Thank You
